version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: track-backend
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - ml_service
    networks:
      - app-network
    restart: unless-stopped

  ml_service:  #указать свой image ml
    image: ml-api
    container_name: ml-service
    ports:
      - "5001:5001"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
