port: "8000"
host: "localhost"

db:
  username: "postgres"
  # password: "XXJGFpgHrNIu8lv4825pfIwdk5yLkkXV"
  host: "localhost"
  port: "5432"
  dbname: "mydb"
  sslmode: "disable"

url: "https://ml-predict-app-production.up.railway.app/predict"
