port: "8000"
host: "localhost"

db:
  username: "track"
  # password: "XXJGFpgHrNIu8lv4825pfIwdk5yLkkXV"
  host: "dpg-cs5pqu5umphs73b0sdmg-a.oregon-postgres.render.com"
  port: "5432"
  dbname: "track_dlme"
  sslmode: "require"

url: "http://localhost:5001/predict"
